### ISSUE TITLE
virl up error on windows

### ISSUE THREAD

**Issue by markheinemann** [CiscoDevNet/virlutils#107]
Hi. Can anyone please help. Thanks

trying to virl up  ( first time user )  and getting error:

##(env) PS C:\Users\mark\Desktop\Documents\Marks Python> virl up virlfiles/spine-leaf                                    
Creating default environment from topology.virl
Exception raised while running your command
Please re-run as 'virl --debug ...' and collect the output before opening an issue
[WinError 3] The system cannot find the path specified: ''

so i ran again with debug:

 C:\Users\mark\Desktop\Documents\Marks Python> virl --debug up virlfiles/spine-leaf                             Creating default environment from topology.virl
Exception raised while running your command
Please open an issue and provide this output:
[WinError 3] The system cannot find the path specified: ''
Traceback (most recent call last):
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\virl\cli\main.py", line 44, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\virl\cli\up\commands.py", line 181, in up1
    server = VIRLServer()
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\virl\api\api.py", line 9, in __init__
    self._host, self._user, self._passwd, self._config = get_credentials()
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\virl\api\credentials.py", line 107, in get_credentials
    host = get_prop("VIRL_HOST")
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\virl\api\credentials.py", line 65, in get_prop
    virl_dir = find_virl()
  File "c:\users\mark\desktop\documents\marks python\env\lib\site-packages\virl\helpers.py", line 86, in find_virl
    if ".virl" in os.listdir(lookin):
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

**Comment by xorrkaz** [comment]
I believe this patch may fix this for you.  But if you created a `.virlrc` file in your current working directory, you shouldn't see this error either:

```diff
diff --git a/virl/helpers.py b/virl/helpers.py
index 5e03d13..c67d38d 100644
--- a/virl/helpers.py
+++ b/virl/helpers.py
@@ -81,6 +81,8 @@ def find_virl():
     while pwd != root:
         if platform.system() == "Windows":
             lookin = "\\".join(pwd)
+            if lookin == "":
+                lookin = "\\"
         else:
             lookin = os.path.join(os.sep, *pwd)
         if ".virl" in os.listdir(lookin):
```
