### ISSUE TITLE
Exception raised due to Controller version 2.2.2+build52 is marked incompatible! 

### ISSUE THREAD

**Issue by etoromol** [CiscoDevNet/virlutils#134]
**Describe the bug**

Exception raised while running any virl command with the following error:

`Controller version 2.2.2+build52 is marked incompatible! List of versions marked explicitly as incompatible: [2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.1, 2.2.2, 2.2.3].
`

**To Reproduce**

1. Go to Terminal
2. Type 'virl ls'
3. Or Type 'cml ls' 

**Expected behavior**

List the labs on the server.

**Desktop (please complete the following information):**
 - OS: macOS Monterrey 12.3
 - Browser: Safari
 - Version 15.4
 - Python 3.9.10
 - virlutils 1.3.7
 - virl2-client 2.3.0

**Debugs**

% virl --debug ls
`Exception raised while running your command
Please open an issue and provide this output:
Controller version 2.2.2+build52 is marked incompatible! List of versions marked explicitly as incompatible: [2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.1, 2.2.2, 2.2.3].
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/virl/cli/main.py", line 45, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/virl/cli/ls/commands.py", line 28, in ls
    client = get_cml_client(server)
  File "/usr/local/lib/python3.9/site-packages/virl/helpers.py", line 344, in get_cml_client
    client = ClientLibrary(server.host, server.user, server.passwd, raise_for_auth_failure=True, ssl_verify=ssl_verify)
  File "/usr/local/lib/python3.9/site-packages/virl2_client/virl2_client.py", line 281, in __init__
    self.check_controller_version()
  File "/usr/local/lib/python3.9/site-packages/virl2_client/virl2_client.py", line 429, in check_controller_version
    raise InitializationError(
virl2_client.virl2_client.InitializationError: Controller version 2.2.2+build52 is marked incompatible! List of versions marked explicitly as incompatible: [2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.1, 2.2.2, 2.2.3].
`

% cml --debug ls
`Exception raised while running your command
Please open an issue and provide this output:
Controller version 2.2.2+build52 is marked incompatible! List of versions marked explicitly as incompatible: [2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.1, 2.2.2, 2.2.3].
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/virl/cli/main.py", line 45, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/virl/cli/ls/commands.py", line 28, in ls
    client = get_cml_client(server)
  File "/usr/local/lib/python3.9/site-packages/virl/helpers.py", line 344, in get_cml_client
    client = ClientLibrary(server.host, server.user, server.passwd, raise_for_auth_failure=True, ssl_verify=ssl_verify)
  File "/usr/local/lib/python3.9/site-packages/virl2_client/virl2_client.py", line 281, in __init__
    self.check_controller_version()
  File "/usr/local/lib/python3.9/site-packages/virl2_client/virl2_client.py", line 429, in check_controller_version
    raise InitializationError(
virl2_client.virl2_client.InitializationError: Controller version 2.2.2+build52 is marked incompatible! List of versions marked explicitly as incompatible: [2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.1, 2.2.2, 2.2.3].`

cat ~/.virlrc 
`VIRL_HOST=10.10.20.161`
`VIRL_USERNAME=developer`
`VIRL_PASSWORD=(the one provided on devnet sandbox)`
`CML_VERIFY_CERT=False`

**Comment by etoromol** [comment]
This error occurs because virlutils 1.3.7 uses virl2-client 2.3.0 who is incompatible with previous versions of CML [2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.1, 2.2.2, 2.2.3]. 

To address this condition, it is required to downgrade your version of virl2-client following the command sequence below:

1. Verify what is your current virl2-client version:
`pip list` or `python3 -m pip list` 

2. Uninstall the current virl2-client package:
`pip uninstall virl2-client` or `python3 -m pip uninstall virl2-client` 

3. Install virl2-client version 2.2.1:
`pip install virl2-client==2.2.1`or `python3 -m install virl2-client==2.2.1`  

If the rest of your configuration if correct, you should be able to connect to your CML instance.

**Comment by xorrkaz** [comment]
Yep, that's right.  I'm a little grumpy that virl2_client doesn't handle the backward compatibility changes, but CML 2.3 has a number of very good improvements and upgrading all your servers is a good idea.
