### ISSUE TITLE
Failed to establish a new connection: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by AkindeleEzekiel** [CiscoDevNet/virlutils#136]
i am trying to connect to a cml lab online. i have created a  varibale (vars) in gitlab which i can link to my development branch.
then i do 
script:
  - echo "$Vars" > /root/.virlrc
  - cat /root/.virlrc

so it copy the variable and moves them to .virlc file in de image: ROckylinux.
... When i run it local it works: sudo gitlab-runner exec docker config-cml
but when i push to gitlab and try to run the pipeline i get this error. Can someone please help

$ cml --debug ls
Exception raised while running your command
Please open an issue and provide this output:
HTTPConnectionPool(host='10.129.28.227', port=19399): Max retries exceeded with url: /simengine/rest/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f36ec748>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last):
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib64/python3.6/http/client.py", line 1269, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1315, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1264, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 978, in send
    self.connect()
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f81f36ec748>: Failed to establish a new connection: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.129.28.227', port=19399): Max retries exceeded with url: /simengine/rest/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f36ec748>: Failed to establish a new connection: [Errno 110] Connection timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/virl/cli/main.py", line 45, in __call__
    return self.main(*args, **kwargs)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/virl/cli/ls/commands.py", line 65, in ls1
    sim_dict = server.list_simulations()
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/virl/api/api.py", line 84, in list_simulations
    r = self.get(url)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/virl/api/api.py", line 53, in get
    r = requests.get(url, auth=(self.user, self.passwd), headers=self._headers)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/builds/ikdoeict/toluwani.akindele/2122-ia-c-cicd-project-akindele-ezekiel/venv/lib64/python3.6/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.129.28.227', port=19399): Max retries exceeded with url: /simengine/rest/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f36ec748>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

**Comment by xorrkaz** [comment]
It would be helpful to actually see your `.virlrc` file.  CML thinks that your server is running VIRL/CML 1.x and trying to connect to that port.  That said, it's getting a connection timeout, so it may be that gitlab-runner container has no network access to your CML server (if it did, it would be able to guess the CML version).  You can also add the following to .virlrc:

```sh
CML2_PLUS="yes"
```

To force it to use CML 2.x.

**Comment by xorrkaz** [comment]
Closing due to timeout.
