### ISSUE TITLE
pyats 'os' attribute for lxc device

### ISSUE THREAD

**Issue by pehruby** [CiscoDevNet/virlutils#71]
**Is your feature request related to a problem? Please describe.**
lxc devices contained in a pyats testbed yaml file which was created using 'virl generate pyats' don't have 'os' attribute defined.

When I want to create a genie testbed using the generated pyats testbed, an AttributeError arises
```
from pyats.topology import loader
from genie.conf import Genie
testbed = loader.load('default_testbed.yaml')
genie_testbed = Genie.init(testbed=testbed)
```
```
Traceback (most recent call last):
  File "pyatstest.py", line 7, in <module>
    genie_testbed = Genie.init(testbed=testbed)
  File "src/genie/conf/main.py", line 90, in genie.conf.main.Genie.init
  File "src/genie/conf/utils/converter.py", line 60, in genie.conf.utils.converter.Converter.convert_tb
  File "src/genie/conf/utils/converter.py", line 131, in genie.conf.utils.converter.Converter.convert_device
  File "src/pyats/topology/device.py", line 439, in pyats.topology.device.Device.__getattr__
AttributeError: 'Device' object has no attribute 'os'
```

**Describe the solution you'd like**

Maybe set os attribute to 'tests' for lxc devices ...

**Comment by kecorbin** [comment]
@pehruby thanks for the issue.  I had noticed this as well.  Not sure the best way to handle it, servers can be used in a pyats testbed for various things.  Hard to balance between making assumptions for completeness - and merely generating a "starting point" 

Related: #58 #70
