### ISSUE TITLE
Deprecate Python 3.3 support and build tests

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/virlutils#73]
**Describe the bug**
TravisCI builds of Python 3.3 are failing because flake8 lint checking and setuptools fail to run due to 
Python version 3.4 or later requirement.

**Proposed Fix**
Deprecated Python 3.3 support as its upstream support was deprecated on 2017-09-19

**Screenshots**
````
$ make lint
flake8
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/flake8/main/application.py", line 17, in <module>
    from flake8.plugins import manager as plugin_manager
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/flake8/plugins/manager.py", line 5, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 90, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
make: *** [lint] Error 1
The command "make lint" exited with 2.
0.28s$ make coverage
coverage run --source=virl setup.py test
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages  # noqa: H301
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 90, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
Coverage.py warning: No data was collected. (no-data-collected)
make: *** [coverage] Error 1
The command "make coverage" exited with 2.
````

**Comment by kecorbin** [comment]
Closed by #74
